
services:
  coffee_auth_app:
    build: .
    container_name: coffee_auth_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - coffee_auth_db
      - coffee_auth_redis
      - coffee_auth_kafka
    networks:
      - coffee_auth_network

  coffee_auth_db:
    image: postgres:17
    container_name: coffee_auth_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - coffee_auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coffee_auth_network

  coffee_auth_redis:
    image: redis:7-alpine
    container_name: coffee_auth_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--save", "60", "1",
      "--maxmemory", "256mb",
      "--maxmemory-policy", "allkeys-lru",
      "--loglevel", "warning"
    ]
    volumes:
      - coffee_auth_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coffee_auth_network

  coffee_auth_kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: coffee_auth_kafka
    environment:
      CLUSTER_ID: n2CAxqxsTFulgzbLi4yn5g

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@coffee_auth_kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://coffee_auth_kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    networks:
      - coffee_auth_network


  worker_vg:
    build: .
    container_name: coffee_auth_worker
    working_dir: /app
    volumes:
      - .:/app
    command: celery -A app.utils.celery_app.celery_app worker --loglevel=info -P solo
    depends_on:
      - coffee_auth_app
      - coffee_auth_db
      - coffee_auth_redis
      - coffee_auth_kafka
    networks:
      - coffee_auth_network

volumes:
  coffee_auth_postgres_data:
  coffee_auth_redis_data:

networks:
  coffee_auth_network:
    driver: bridge
