apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: auth-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery
          image: your-dockerhub/coffee-auth-service:latest
          command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: POSTGRES_USER
              value: "authuser"
            - name: POSTGRES_PASSWORD
              value: "authpassword"
            - name: POSTGRES_DB
              value: "authdb"
            - name: POSTGRES_HOST
              value: "postgres.auth-dev.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
